-- MySQL Script generated by MySQL Workbench
-- Thu Mar 26 21:21:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ebdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ebdb` ;

-- -----------------------------------------------------
-- Schema ebdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ebdb` DEFAULT CHARACTER SET utf8 ;
USE `ebdb` ;

-- -----------------------------------------------------
-- Table `ebdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`users` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `currentBalance` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebdb`.`users_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`users_roles` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`users_roles` (
  `roleId` INT NOT NULL AUTO_INCREMENT,
  `roleType` VARCHAR(45) NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`roleId`, `userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebdb`.`stocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`stocks` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`stocks` (
  `stockId` INT NOT NULL AUTO_INCREMENT,
  `symbol` VARCHAR(45) NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `ownedUnits` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`stockId`, `userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebdb`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`transactions` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`transactions` (
  `transactionId` INT NOT NULL AUTO_INCREMENT,
  `amountTraded` INT NOT NULL,
  `symbol` VARCHAR(45) NOT NULL,
  `transactionDateTime` DATETIME NOT NULL,
  `stockPriceAtPurchase` DECIMAL(9,2) NOT NULL,
  `transactionType` ENUM("BUY", "SELL") NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`transactionId`, `userId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
